//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.infonavit.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infonavit.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StatusCaso_QNAME = new QName("http://ws.infonavit.com/", "statusCaso");
    private final static QName _ValidarCredito_QNAME = new QName("http://ws.infonavit.com/", "validarCredito");
    private final static QName _ValidarCreditoResponse_QNAME = new QName("http://ws.infonavit.com/", "validarCreditoResponse");
    private final static QName _StatusCasoResponse_QNAME = new QName("http://ws.infonavit.com/", "statusCasoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infonavit.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatusCasoResponse }
     * 
     */
    public StatusCasoResponse createStatusCasoResponse() {
        return new StatusCasoResponse();
    }

    /**
     * Create an instance of {@link ValidarCreditoResponse }
     * 
     */
    public ValidarCreditoResponse createValidarCreditoResponse() {
        return new ValidarCreditoResponse();
    }

    /**
     * Create an instance of {@link ValidarCredito }
     * 
     */
    public ValidarCredito createValidarCredito() {
        return new ValidarCredito();
    }

    /**
     * Create an instance of {@link StatusCaso }
     * 
     */
    public StatusCaso createStatusCaso() {
        return new StatusCaso();
    }

    /**
     * Create an instance of {@link InfoPms }
     * 
     */
    public InfoPms createInfoPms() {
        return new InfoPms();
    }

    /**
     * Create an instance of {@link InfoStatusCaso }
     * 
     */
    public InfoStatusCaso createInfoStatusCaso() {
        return new InfoStatusCaso();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusCaso }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.infonavit.com/", name = "statusCaso")
    public JAXBElement<StatusCaso> createStatusCaso(StatusCaso value) {
        return new JAXBElement<StatusCaso>(_StatusCaso_QNAME, StatusCaso.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidarCredito }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.infonavit.com/", name = "validarCredito")
    public JAXBElement<ValidarCredito> createValidarCredito(ValidarCredito value) {
        return new JAXBElement<ValidarCredito>(_ValidarCredito_QNAME, ValidarCredito.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidarCreditoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.infonavit.com/", name = "validarCreditoResponse")
    public JAXBElement<ValidarCreditoResponse> createValidarCreditoResponse(ValidarCreditoResponse value) {
        return new JAXBElement<ValidarCreditoResponse>(_ValidarCreditoResponse_QNAME, ValidarCreditoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusCasoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.infonavit.com/", name = "statusCasoResponse")
    public JAXBElement<StatusCasoResponse> createStatusCasoResponse(StatusCasoResponse value) {
        return new JAXBElement<StatusCasoResponse>(_StatusCasoResponse_QNAME, StatusCasoResponse.class, null, value);
    }

}
