//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.pms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Pms", targetNamespace = "http://ws.infonavit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Pms {


    /**
     * 
     * @param fechaEmisionCarta
     * @param cartaDeCancelacion
     * @param numeroDeCaso
     * @param status
     * @param tipoOperacion
     * @param nombreAcreditado
     * @param descripcion
     * @param entidad
     * @param numeroDeCredito
     * @return
     *     returns com.gisnet.cancelacion.wsclient.pms.InfoPms
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarCredito", targetNamespace = "http://ws.infonavit.com/", className = "com.gisnet.cancelacion.wsclient.pms.ValidarCredito")
    @ResponseWrapper(localName = "validarCreditoResponse", targetNamespace = "http://ws.infonavit.com/", className = "com.gisnet.cancelacion.wsclient.pms.ValidarCreditoResponse")
    public InfoPms validarCredito(
        @WebParam(name = "numeroDeCredito", targetNamespace = "")
        int numeroDeCredito,
        @WebParam(name = "numeroDeCaso", targetNamespace = "")
        int numeroDeCaso,
        @WebParam(name = "entidad", targetNamespace = "")
        String entidad,
        @WebParam(name = "status", targetNamespace = "")
        int status,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "cartaDeCancelacion", targetNamespace = "")
        byte[] cartaDeCancelacion,
        @WebParam(name = "fechaEmisionCarta", targetNamespace = "")
        XMLGregorianCalendar fechaEmisionCarta,
        @WebParam(name = "nombreAcreditado", targetNamespace = "")
        String nombreAcreditado,
        @WebParam(name = "tipoOperacion", targetNamespace = "")
        int tipoOperacion);

    /**
     * 
     * @param fechaEmisionCarta
     * @param cartaDeCancelacion
     * @param numeroDeCaso
     * @param status
     * @param tipoOperacion
     * @param nombreAcreditado
     * @param descripcion
     * @param entidad
     * @param numeroDeCredito
     * @return
     *     returns com.gisnet.cancelacion.wsclient.pms.InfoStatusCaso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "statusCaso", targetNamespace = "http://ws.infonavit.com/", className = "com.gisnet.cancelacion.wsclient.pms.StatusCaso")
    @ResponseWrapper(localName = "statusCasoResponse", targetNamespace = "http://ws.infonavit.com/", className = "com.gisnet.cancelacion.wsclient.pms.StatusCasoResponse")
    public InfoStatusCaso statusCaso(
        @WebParam(name = "numeroDeCredito", targetNamespace = "")
        int numeroDeCredito,
        @WebParam(name = "numeroDeCaso", targetNamespace = "")
        int numeroDeCaso,
        @WebParam(name = "entidad", targetNamespace = "")
        String entidad,
        @WebParam(name = "status", targetNamespace = "")
        int status,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "cartaDeCancelacion", targetNamespace = "")
        byte[] cartaDeCancelacion,
        @WebParam(name = "fechaEmisionCarta", targetNamespace = "")
        XMLGregorianCalendar fechaEmisionCarta,
        @WebParam(name = "nombreAcreditado", targetNamespace = "")
        String nombreAcreditado,
        @WebParam(name = "tipoOperacion", targetNamespace = "")
        int tipoOperacion);

}
