//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.pms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for statusCaso complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statusCaso">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroDeCredito" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numeroDeCaso" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cartaDeCancelacion" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="fechaEmisionCarta" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="nombreAcreditado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoOperacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statusCaso", propOrder = {
    "numeroDeCredito",
    "numeroDeCaso",
    "entidad",
    "status",
    "descripcion",
    "cartaDeCancelacion",
    "fechaEmisionCarta",
    "nombreAcreditado",
    "tipoOperacion"
})
public class StatusCaso {

    protected int numeroDeCredito;
    protected int numeroDeCaso;
    protected String entidad;
    protected int status;
    protected String descripcion;
    protected byte[] cartaDeCancelacion;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEmisionCarta;
    protected String nombreAcreditado;
    protected int tipoOperacion;

    /**
     * Gets the value of the numeroDeCredito property.
     * 
     */
    public int getNumeroDeCredito() {
        return numeroDeCredito;
    }

    /**
     * Sets the value of the numeroDeCredito property.
     * 
     */
    public void setNumeroDeCredito(int value) {
        this.numeroDeCredito = value;
    }

    /**
     * Gets the value of the numeroDeCaso property.
     * 
     */
    public int getNumeroDeCaso() {
        return numeroDeCaso;
    }

    /**
     * Sets the value of the numeroDeCaso property.
     * 
     */
    public void setNumeroDeCaso(int value) {
        this.numeroDeCaso = value;
    }

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the cartaDeCancelacion property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCartaDeCancelacion() {
        return cartaDeCancelacion;
    }

    /**
     * Sets the value of the cartaDeCancelacion property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCartaDeCancelacion(byte[] value) {
        this.cartaDeCancelacion = ((byte[]) value);
    }

    /**
     * Gets the value of the fechaEmisionCarta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEmisionCarta() {
        return fechaEmisionCarta;
    }

    /**
     * Sets the value of the fechaEmisionCarta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEmisionCarta(XMLGregorianCalendar value) {
        this.fechaEmisionCarta = value;
    }

    /**
     * Gets the value of the nombreAcreditado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreAcreditado() {
        return nombreAcreditado;
    }

    /**
     * Sets the value of the nombreAcreditado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreAcreditado(String value) {
        this.nombreAcreditado = value;
    }

    /**
     * Gets the value of the tipoOperacion property.
     * 
     */
    public int getTipoOperacion() {
        return tipoOperacion;
    }

    /**
     * Sets the value of the tipoOperacion property.
     * 
     */
    public void setTipoOperacion(int value) {
        this.tipoOperacion = value;
    }

}
