//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.autenticacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "LDAPConnectionJAAS", targetNamespace = "http://infonavit.ejemplo.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LDAPConnectionJAAS {


    /**
     * 
     * @param pwd
     * @param usua
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "loguearReturn", targetNamespace = "")
    @RequestWrapper(localName = "loguear", targetNamespace = "http://infonavit.ejemplo.com", className = "com.gisnet.cancelacion.wsclient.autenticacion.Loguear")
    @ResponseWrapper(localName = "loguearResponse", targetNamespace = "http://infonavit.ejemplo.com", className = "com.gisnet.cancelacion.wsclient.autenticacion.LoguearResponse")
    public String loguear(
        @WebParam(name = "usua", targetNamespace = "")
        String usua,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd);

}
