//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inputParameter1" type="{http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled}Input" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputParameter1"
})
@XmlRootElement(name = "ConsultaNotarios")
public class ConsultaNotarios {

    protected Input inputParameter1;

    /**
     * Gets the value of the inputParameter1 property.
     * 
     * @return
     *     possible object is
     *     {@link Input }
     *     
     */
    public Input getInputParameter1() {
        return inputParameter1;
    }

    /**
     * Sets the value of the inputParameter1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Input }
     *     
     */
    public void setInputParameter1(Input value) {
        this.inputParameter1 = value;
    }

}
