//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * tipo dato respuesta cancelacion
 * 
 * <p>Java class for DT_CANCELACION_RESP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DT_CANCELACION_RESP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosCredito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numeroCredito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="estatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="procede" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fechaLiquidacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="numeroCaso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DatosNotario" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="codigoNotario" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="nombrenotario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="notaria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="convenioInfonavit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="correoElectronico" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DT_CANCELACION_RESP", propOrder = {
    "datosCredito",
    "datosNotario"
})
public class DTCANCELACIONRESP {

    @XmlElement(name = "DatosCredito")
    protected DTCANCELACIONRESP.DatosCredito datosCredito;
    @XmlElement(name = "DatosNotario")
    protected List<DTCANCELACIONRESP.DatosNotario> datosNotario;

    /**
     * Gets the value of the datosCredito property.
     * 
     * @return
     *     possible object is
     *     {@link DTCANCELACIONRESP.DatosCredito }
     *     
     */
    public DTCANCELACIONRESP.DatosCredito getDatosCredito() {
        return datosCredito;
    }

    /**
     * Sets the value of the datosCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTCANCELACIONRESP.DatosCredito }
     *     
     */
    public void setDatosCredito(DTCANCELACIONRESP.DatosCredito value) {
        this.datosCredito = value;
    }

    /**
     * Gets the value of the datosNotario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datosNotario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatosNotario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DTCANCELACIONRESP.DatosNotario }
     * 
     * 
     */
    public List<DTCANCELACIONRESP.DatosNotario> getDatosNotario() {
        if (datosNotario == null) {
            datosNotario = new ArrayList<DTCANCELACIONRESP.DatosNotario>();
        }
        return this.datosNotario;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numeroCredito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="estatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="procede" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fechaLiquidacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="numeroCaso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numeroCredito",
        "estatus",
        "descripcion",
        "direccion",
        "procede",
        "entidad",
        "fechaLiquidacion",
        "numeroCaso"
    })
    public static class DatosCredito {

        protected String numeroCredito;
        protected String estatus;
        protected String descripcion;
        protected String direccion;
        protected Boolean procede;
        protected String entidad;
        protected String fechaLiquidacion;
        protected String numeroCaso;

        /**
         * Gets the value of the numeroCredito property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroCredito() {
            return numeroCredito;
        }

        /**
         * Sets the value of the numeroCredito property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroCredito(String value) {
            this.numeroCredito = value;
        }

        /**
         * Gets the value of the estatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstatus() {
            return estatus;
        }

        /**
         * Sets the value of the estatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstatus(String value) {
            this.estatus = value;
        }

        /**
         * Gets the value of the descripcion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescripcion() {
            return descripcion;
        }

        /**
         * Sets the value of the descripcion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescripcion(String value) {
            this.descripcion = value;
        }

        /**
         * Gets the value of the direccion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDireccion() {
            return direccion;
        }

        /**
         * Sets the value of the direccion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDireccion(String value) {
            this.direccion = value;
        }

        /**
         * Gets the value of the procede property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isProcede() {
            return procede;
        }

        /**
         * Sets the value of the procede property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setProcede(Boolean value) {
            this.procede = value;
        }

        /**
         * Gets the value of the entidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntidad() {
            return entidad;
        }

        /**
         * Sets the value of the entidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntidad(String value) {
            this.entidad = value;
        }

        /**
         * Gets the value of the fechaLiquidacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaLiquidacion() {
            return fechaLiquidacion;
        }

        /**
         * Sets the value of the fechaLiquidacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaLiquidacion(String value) {
            this.fechaLiquidacion = value;
        }

        /**
         * Gets the value of the numeroCaso property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroCaso() {
            return numeroCaso;
        }

        /**
         * Sets the value of the numeroCaso property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroCaso(String value) {
            this.numeroCaso = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="codigoNotario" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="nombrenotario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="notaria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="convenioInfonavit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="correoElectronico" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codigoNotario",
        "nombrenotario",
        "notaria",
        "entidad",
        "convenioInfonavit",
        "correoElectronico",
        "telefono"
    })
    public static class DatosNotario {

        protected BigInteger codigoNotario;
        protected String nombrenotario;
        protected String notaria;
        protected String entidad;
        protected String convenioInfonavit;
        protected String correoElectronico;
        protected String telefono;

        /**
         * Gets the value of the codigoNotario property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCodigoNotario() {
            return codigoNotario;
        }

        /**
         * Sets the value of the codigoNotario property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCodigoNotario(BigInteger value) {
            this.codigoNotario = value;
        }

        /**
         * Gets the value of the nombrenotario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombrenotario() {
            return nombrenotario;
        }

        /**
         * Sets the value of the nombrenotario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombrenotario(String value) {
            this.nombrenotario = value;
        }

        /**
         * Gets the value of the notaria property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotaria() {
            return notaria;
        }

        /**
         * Sets the value of the notaria property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotaria(String value) {
            this.notaria = value;
        }

        /**
         * Gets the value of the entidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntidad() {
            return entidad;
        }

        /**
         * Sets the value of the entidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntidad(String value) {
            this.entidad = value;
        }

        /**
         * Gets the value of the convenioInfonavit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConvenioInfonavit() {
            return convenioInfonavit;
        }

        /**
         * Sets the value of the convenioInfonavit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConvenioInfonavit(String value) {
            this.convenioInfonavit = value;
        }

        /**
         * Gets the value of the correoElectronico property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCorreoElectronico() {
            return correoElectronico;
        }

        /**
         * Sets the value of the correoElectronico property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCorreoElectronico(String value) {
            this.correoElectronico = value;
        }

        /**
         * Gets the value of the telefono property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefono() {
            return telefono;
        }

        /**
         * Sets the value of the telefono property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefono(String value) {
            this.telefono = value;
        }

    }

}
