//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gisnet.cancelacion.wsclient.microflujo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gisnet.cancelacion.wsclient.microflujo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaNotarios }
     * 
     */
    public ConsultaNotarios createConsultaNotarios() {
        return new ConsultaNotarios();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link OperacionPrincipalResponse }
     * 
     */
    public OperacionPrincipalResponse createOperacionPrincipalResponse() {
        return new OperacionPrincipalResponse();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link OperacionPrincipal }
     * 
     */
    public OperacionPrincipal createOperacionPrincipal() {
        return new OperacionPrincipal();
    }

    /**
     * Create an instance of {@link ConsultaNotariosResponse }
     * 
     */
    public ConsultaNotariosResponse createConsultaNotariosResponse() {
        return new ConsultaNotariosResponse();
    }

    /**
     * Create an instance of {@link DatosNotarios }
     * 
     */
    public DatosNotarios createDatosNotarios() {
        return new DatosNotarios();
    }

    /**
     * Create an instance of {@link RegistraCaso }
     * 
     */
    public RegistraCaso createRegistraCaso() {
        return new RegistraCaso();
    }

    /**
     * Create an instance of {@link RegistraCasoResponse }
     * 
     */
    public RegistraCasoResponse createRegistraCasoResponse() {
        return new RegistraCasoResponse();
    }

    /**
     * Create an instance of {@link Estatus }
     * 
     */
    public Estatus createEstatus() {
        return new Estatus();
    }

    /**
     * Create an instance of {@link ValidarCreditoResponse }
     * 
     */
    public ValidarCreditoResponse createValidarCreditoResponse() {
        return new ValidarCreditoResponse();
    }

    /**
     * Create an instance of {@link DatosCredito }
     * 
     */
    public DatosCredito createDatosCredito() {
        return new DatosCredito();
    }

    /**
     * Create an instance of {@link ValidarCredito }
     * 
     */
    public ValidarCredito createValidarCredito() {
        return new ValidarCredito();
    }

    /**
     * Create an instance of {@link CambioEstatusResponse }
     * 
     */
    public CambioEstatusResponse createCambioEstatusResponse() {
        return new CambioEstatusResponse();
    }

    /**
     * Create an instance of {@link CambioEstatus }
     * 
     */
    public CambioEstatus createCambioEstatus() {
        return new CambioEstatus();
    }

}
