//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gisnet.cancelacion.wsclient.microflujo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MTCANCELACIONRESP_QNAME = new QName("http://infonavit.org.mx/Cancelacion_ARPP", "MT_CANCELACION_RESP");
    private final static QName _MTCANCELACIONRQST_QNAME = new QName("http://infonavit.org.mx/Cancelacion_ARPP", "MT_CANCELACION_RQST");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gisnet.cancelacion.wsclient.microflujo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DTCANCELACIONRESP }
     * 
     */
    public DTCANCELACIONRESP createDTCANCELACIONRESP() {
        return new DTCANCELACIONRESP();
    }

    /**
     * Create an instance of {@link DTCANCELACIONREQ }
     * 
     */
    public DTCANCELACIONREQ createDTCANCELACIONREQ() {
        return new DTCANCELACIONREQ();
    }

    /**
     * Create an instance of {@link DTCANCELACIONRESP.DatosCredito }
     * 
     */
    public DTCANCELACIONRESP.DatosCredito createDTCANCELACIONRESPDatosCredito() {
        return new DTCANCELACIONRESP.DatosCredito();
    }

    /**
     * Create an instance of {@link DTCANCELACIONRESP.DatosNotario }
     * 
     */
    public DTCANCELACIONRESP.DatosNotario createDTCANCELACIONRESPDatosNotario() {
        return new DTCANCELACIONRESP.DatosNotario();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTCANCELACIONRESP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://infonavit.org.mx/Cancelacion_ARPP", name = "MT_CANCELACION_RESP")
    public JAXBElement<DTCANCELACIONRESP> createMTCANCELACIONRESP(DTCANCELACIONRESP value) {
        return new JAXBElement<DTCANCELACIONRESP>(_MTCANCELACIONRESP_QNAME, DTCANCELACIONRESP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTCANCELACIONREQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://infonavit.org.mx/Cancelacion_ARPP", name = "MT_CANCELACION_RQST")
    public JAXBElement<DTCANCELACIONREQ> createMTCANCELACIONRQST(DTCANCELACIONREQ value) {
        return new JAXBElement<DTCANCELACIONREQ>(_MTCANCELACIONRQST_QNAME, DTCANCELACIONREQ.class, null, value);
    }

}
