//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Output complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Output">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosCredito" type="{http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled}DatosCredito" minOccurs="0"/>
 *         &lt;element name="DatosNotario" type="{http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled}DatosNotarios" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Output", namespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled", propOrder = {
    "datosCredito",
    "datosNotario"
})
public class Output {

    @XmlElement(name = "DatosCredito")
    protected DatosCredito datosCredito;
    @XmlElement(name = "DatosNotario")
    protected DatosNotarios datosNotario;

    /**
     * Gets the value of the datosCredito property.
     * 
     * @return
     *     possible object is
     *     {@link DatosCredito }
     *     
     */
    public DatosCredito getDatosCredito() {
        return datosCredito;
    }

    /**
     * Sets the value of the datosCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosCredito }
     *     
     */
    public void setDatosCredito(DatosCredito value) {
        this.datosCredito = value;
    }

    /**
     * Gets the value of the datosNotario property.
     * 
     * @return
     *     possible object is
     *     {@link DatosNotarios }
     *     
     */
    public DatosNotarios getDatosNotario() {
        return datosNotario;
    }

    /**
     * Sets the value of the datosNotario property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosNotarios }
     *     
     */
    public void setDatosNotario(DatosNotarios value) {
        this.datosNotario = value;
    }

}
