//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow")
package com.gisnet.cancelacion.wsclient.microflujo;
