//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "SI_CANCELACION_OU", targetNamespace = "http://infonavit.org.mx/Cancelacion_ARPP")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SICANCELACIONOU {


    /**
     * 
     * @param mtCANCELACIONRQST
     * @return
     *     returns com.gisnet.cancelacion.wsclient.microflujo.DTCANCELACIONRESP
     */
    @WebMethod(operationName = "SI_CANCELACION_OU", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_CANCELACION_RESP", targetNamespace = "http://infonavit.org.mx/Cancelacion_ARPP", partName = "MT_CANCELACION_RESP")
    public DTCANCELACIONRESP siCANCELACIONOU(
        @WebParam(name = "MT_CANCELACION_RQST", targetNamespace = "http://infonavit.org.mx/Cancelacion_ARPP", partName = "MT_CANCELACION_RQST")
        DTCANCELACIONREQ mtCANCELACIONRQST);

}
