//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SI_CANCELACION_OUService", targetNamespace = "http://infonavit.org.mx/Cancelacion_ARPP", wsdlLocation = "WEB-INF/wsdl/Cancelacion_microflujo_PI.wsdl")
public class SICANCELACIONOUService
    extends Service
{

    private final static URL SICANCELACIONOUSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICANCELACIONOUSERVICE_EXCEPTION;
    private final static QName SICANCELACIONOUSERVICE_QNAME = new QName("http://infonavit.org.mx/Cancelacion_ARPP", "SI_CANCELACION_OUService");

    static {
            SICANCELACIONOUSERVICE_WSDL_LOCATION = com.gisnet.cancelacion.wsclient.microflujo.SICANCELACIONOUService.class.getResource("/WEB-INF/wsdl/Cancelacion_microflujo_PI.wsdl");
        WebServiceException e = null;
        if (SICANCELACIONOUSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/Cancelacion_microflujo_PI.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SICANCELACIONOUSERVICE_EXCEPTION = e;
    }

    public SICANCELACIONOUService() {
        super(__getWsdlLocation(), SICANCELACIONOUSERVICE_QNAME);
    }

    public SICANCELACIONOUService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICANCELACIONOUSERVICE_QNAME, features);
    }

    public SICANCELACIONOUService(URL wsdlLocation) {
        super(wsdlLocation, SICANCELACIONOUSERVICE_QNAME);
    }

    public SICANCELACIONOUService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICANCELACIONOUSERVICE_QNAME, features);
    }

    public SICANCELACIONOUService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICANCELACIONOUService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICANCELACIONOU
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICANCELACIONOU getHTTPPort() {
        return super.getPort(new QName("http://infonavit.org.mx/Cancelacion_ARPP", "HTTP_Port"), SICANCELACIONOU.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICANCELACIONOU
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICANCELACIONOU getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infonavit.org.mx/Cancelacion_ARPP", "HTTP_Port"), SICANCELACIONOU.class, features);
    }

    /**
     * 
     * @return
     *     returns SICANCELACIONOU
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICANCELACIONOU getHTTPSPort() {
        return super.getPort(new QName("http://infonavit.org.mx/Cancelacion_ARPP", "HTTPS_Port"), SICANCELACIONOU.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICANCELACIONOU
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICANCELACIONOU getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infonavit.org.mx/Cancelacion_ARPP", "HTTPS_Port"), SICANCELACIONOU.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICANCELACIONOUSERVICE_EXCEPTION!= null) {
            throw SICANCELACIONOUSERVICE_EXCEPTION;
        }
        return SICANCELACIONOUSERVICE_WSDL_LOCATION;
    }

}
