//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "StartFlow", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", wsdlLocation = "WEB-INF/wsdl/sap.com_home.infonavit_po_ch.bl.caf_StartFlow.wsdl")
public class StartFlowClient
    extends Service
{

    private final static URL STARTFLOW_WSDL_LOCATION;
    private final static WebServiceException STARTFLOW_EXCEPTION;
    private final static QName STARTFLOW_QNAME = new QName("http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", "StartFlow");

    static {
            STARTFLOW_WSDL_LOCATION = com.gisnet.cancelacion.wsclient.microflujo.StartFlowClient.class.getResource("/WEB-INF/wsdl/sap.com_home.infonavit_po_ch.bl.caf_StartFlow.wsdl");
        WebServiceException e = null;
        if (STARTFLOW_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/sap.com_home.infonavit_po_ch.bl.caf_StartFlow.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        STARTFLOW_EXCEPTION = e;
    }

    public StartFlowClient() {
        super(__getWsdlLocation(), STARTFLOW_QNAME);
    }

    public StartFlowClient(WebServiceFeature... features) {
        super(__getWsdlLocation(), STARTFLOW_QNAME, features);
    }

    public StartFlowClient(URL wsdlLocation) {
        super(wsdlLocation, STARTFLOW_QNAME);
    }

    public StartFlowClient(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STARTFLOW_QNAME, features);
    }

    public StartFlowClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StartFlowClient(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StartFlowSEI
     */
    @WebEndpoint(name = "StartFlowBindingPort")
    public StartFlowSEI getStartFlowBindingPort() {
        return super.getPort(new QName("http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", "StartFlowBindingPort"), StartFlowSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StartFlowSEI
     */
    @WebEndpoint(name = "StartFlowBindingPort")
    public StartFlowSEI getStartFlowBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", "StartFlowBindingPort"), StartFlowSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STARTFLOW_EXCEPTION!= null) {
            throw STARTFLOW_EXCEPTION;
        }
        return STARTFLOW_WSDL_LOCATION;
    }

}
