//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.gisnet.cancelacion.wsclient.microflujo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "StartFlow", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StartFlowSEI {


    /**
     * 
     * @param inputParameter1
     * @return
     *     returns com.gisnet.cancelacion.wsclient.microflujo.Estatus
     */
    @WebMethod(operationName = "CambioEstatus", action = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow/CambioEstatus")
    @WebResult(name = "outputParameter1", targetNamespace = "")
    @RequestWrapper(localName = "CambioEstatus", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.CambioEstatus")
    @ResponseWrapper(localName = "CambioEstatusResponse", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.CambioEstatusResponse")
    public Estatus cambioEstatus(
        @WebParam(name = "inputParameter1", targetNamespace = "")
        Input inputParameter1);

    /**
     * 
     * @param inputParameter1
     * @return
     *     returns com.gisnet.cancelacion.wsclient.microflujo.DatosNotarios
     */
    @WebMethod(operationName = "ConsultaNotarios", action = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow/ConsultaNotarios")
    @WebResult(name = "outputParameter1", targetNamespace = "")
    @RequestWrapper(localName = "ConsultaNotarios", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.ConsultaNotarios")
    @ResponseWrapper(localName = "ConsultaNotariosResponse", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.ConsultaNotariosResponse")
    public DatosNotarios consultaNotarios(
        @WebParam(name = "inputParameter1", targetNamespace = "")
        Input inputParameter1);

    /**
     * 
     * @param inputParameter1
     * @return
     *     returns com.gisnet.cancelacion.wsclient.microflujo.Estatus
     */
    @WebMethod(operationName = "RegistraCaso", action = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow/RegistraCaso")
    @WebResult(name = "outputParameter1", targetNamespace = "")
    @RequestWrapper(localName = "RegistraCaso", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.RegistraCaso")
    @ResponseWrapper(localName = "RegistraCasoResponse", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.RegistraCasoResponse")
    public Estatus registraCaso(
        @WebParam(name = "inputParameter1", targetNamespace = "")
        Input inputParameter1);

    /**
     * 
     * @param inputParameter1
     * @return
     *     returns com.gisnet.cancelacion.wsclient.microflujo.DatosCredito
     */
    @WebMethod(action = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow/validarCredito")
    @WebResult(name = "outputParameter1", targetNamespace = "")
    @RequestWrapper(localName = "validarCredito", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.ValidarCredito")
    @ResponseWrapper(localName = "validarCreditoResponse", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.ValidarCreditoResponse")
    public DatosCredito validarCredito(
        @WebParam(name = "inputParameter1", targetNamespace = "")
        Input inputParameter1);

    /**
     * 
     * @param inputParameter1
     * @return
     *     returns com.gisnet.cancelacion.wsclient.microflujo.Output
     */
    @WebMethod(operationName = "OperacionPrincipal", action = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow/OperacionPrincipal")
    @WebResult(name = "outputParameter1", targetNamespace = "")
    @RequestWrapper(localName = "OperacionPrincipal", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.OperacionPrincipal")
    @ResponseWrapper(localName = "OperacionPrincipalResponse", targetNamespace = "http://www.sap.com/caf/sap.com/home.infonavit_po_ch.bl.caf/modeled/StartFlow", className = "com.gisnet.cancelacion.wsclient.microflujo.OperacionPrincipalResponse")
    public Output operacionPrincipal(
        @WebParam(name = "inputParameter1", targetNamespace = "")
        Input inputParameter1);

}
